CREATE TABLE IF NOT EXISTS public.role_titles (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  title      text        NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.role_titles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "role_titles_select" ON public.role_titles
  FOR SELECT USING (true);

-- Seed
INSERT INTO public.role_titles (title) VALUES
  ('Frontend Developer'),
  ('Backend Developer'),
  ('Full Stack Developer'),
  ('Mobile Developer (iOS)'),
  ('Mobile Developer (Android)'),
  ('React Developer'),
  ('Vue.js Developer'),
  ('Node.js Developer'),
  ('Python Developer'),
  ('Ruby on Rails Developer'),
  ('PHP Developer'),
  ('Go Developer'),
  ('DevOps Engineer'),
  ('Cloud Architect'),
  ('AWS Solutions Architect'),
  ('Data Engineer'),
  ('Machine Learning Engineer'),
  ('AI Engineer'),
  ('QA / Test Automation Engineer'),
  ('Site Reliability Engineer'),
  ('Security Engineer'),
  ('Blockchain Developer'),
  ('WordPress Developer'),
  ('Shopify Developer'),
  ('Salesforce Developer'),
  ('UI Designer'),
  ('UX Designer'),
  ('UI/UX Designer'),
  ('Product Designer'),
  ('Graphic Designer'),
  ('Motion Designer'),
  ('Brand Designer'),
  ('Web Designer'),
  ('Illustrator'),
  ('Video Editor'),
  ('3D Artist / Designer'),
  ('Logo Designer'),
  ('Product Manager'),
  ('Technical Product Manager'),
  ('Product Owner'),
  ('Growth Product Manager'),
  ('Digital Marketing Manager'),
  ('SEO Specialist'),
  ('Content Strategist'),
  ('Social Media Manager'),
  ('Performance Marketing Manager'),
  ('Email Marketing Specialist'),
  ('Affiliate Marketing Manager'),
  ('PPC / Paid Ads Specialist'),
  ('Marketing Analyst'),
  ('Brand Strategist'),
  ('Community Manager'),
  ('Sales Development Representative'),
  ('Account Executive'),
  ('Business Development Manager'),
  ('Sales Manager'),
  ('Customer Success Manager'),
  ('Customer Support Specialist'),
  ('Technical Support Specialist'),
  ('Onboarding Specialist'),
  ('Bookkeeper'),
  ('Accountant'),
  ('Financial Analyst'),
  ('Virtual Assistant'),
  ('Executive Assistant'),
  ('Operations Manager'),
  ('Project Manager'),
  ('Business Analyst'),
  ('Content Writer'),
  ('Copywriter'),
  ('Technical Writer'),
  ('Ghostwriter'),
  ('Proofreader / Editor'),
  ('Scriptwriter'),
  ('Podcast Editor'),
  ('Video Content Creator'),
  ('Data Analyst'),
  ('Data Scientist'),
  ('Business Intelligence Analyst'),
  ('Analytics Engineer'),
  ('Recruiter'),
  ('HR Manager'),
  ('Talent Acquisition Specialist'),
  ('HR Generalist'),
  ('Legal Researcher'),
  ('Paralegal'),
  ('Online Tutor'),
  ('Instructional Designer'),
  ('eLearning Developer'),
  ('Medical Transcriptionist'),
  ('Healthcare Data Analyst'),
  ('Research Analyst'),
  ('E-commerce Specialist'),
  ('Amazon FBA Specialist'),
  ('CRM Specialist'),
  ('Salesforce Administrator'),
  ('HubSpot Specialist'),
  ('Zapier / Automation Specialist'),
  ('Social Media Content Creator'),
  ('Public Relations Specialist'),
  ('Translation Specialist'),
  ('Transcriptionist'),
  ('Cybersecurity Analyst'),
  ('IT Support Specialist'),
  ('Database Administrator'),
  ('Systems Administrator'),
  ('Network Engineer'),
  ('Embedded Systems Engineer')
ON CONFLICT (title) DO NOTHING;
